name: "Edil Style Website"
description: "Website for Edil Style"
version: "1.0.0"
slug: "edil_style"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web interface"
webui: "http://[HOST]:[PORT:3000]"
ingress: true
ingress_port: 3000
panel_icon: mdi:web
panel_title: "Edil Style"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)? 