name: "Edil Style Website"
description: "Website for Edil Style"
version: "1.0.0"
slug: "edil_style"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
ports:
  3890/tcp: 3890
ports_description:
  3890/tcp: "Web interface"
webui: "http://[HOST]:[PORT:3890]"
ingress: true
ingress_port: 3890
panel_icon: mdi:web
panel_title: "Edil Style"
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
